### ISSUE TITLE
10-25 base images regular update

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/dnceng#1063]
### Release Note Category

- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Update regular base images.

**Comment by v-zheyan** [comment]
Related task: https://dnceng.visualstudio.com/internal/_workitems/edit/5627/

**Comment by dougbu** [comment]
@ilyas1974 I thought 17.5.5 and 17.8 p4 were too new for rolling out next week❔ I'm fine if you are of course.

@v-zheyan we just completed a production build of helix-machines that updated the regular preview 2022 image from P1 to P2. No need for changes to that image, especially because using a new p2 base image again will require us to revert our move to consistent base OSes. we need to decide exact what fixes we're going to apply this week and the order. please disable autocomplete on !34522 for now

**Comment by v-zheyan** [comment]
@dougbu @ilyas1974 Sorry for not seeing your message in time. 34522 has merged but failed to build.
https://dev.azure.com/dnceng/internal/_build/results?buildId=2295178&view=results
the corresponding images haven't been built successfully. So we still use the old version.

**Comment by dougbu** [comment]
@v-zheyan it's fine. we have another variables.json change to do. We're going to use 17.8 p3 in the regular preview image (not P2). just a small touch up in this issue (which I'll do) and a new variables.json PR. I'll cover the PR tomorrow morning if you don't get to it.

**Comment by dougbu** [comment]
my concern is image-generation will create another Datacenter 2019 queue w/o separate changes. I'm going to work on those tomorrow. don't worry about running image-generation in the meantime (after the new variables.json PR is merged)
