### ISSUE TITLE
Validation Strategy for Helix-Machines change on macOS systems 

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#1069]
While we currently do a good job of validating changes we make to helix-machines on Linux and Windows systems, we have a hole when it comes to macOS systems as well as on-premises systems.

We need to create a validation process/strategy that allows us to make sure that "global" changes we made to Helix-Machines (i.e. CG changes) do not break our production macOS systems.

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

As an interim measure to improve our on-prem validation story, changed one pipeline validation job to test our most problematic on-prem queue (osx.13.arm64).

**Comment by dougbu** [comment]
one of my PRs (likely a draft) switch our on-prem validation job to the oddest and historically most problematic OSX machines &mdash; , osx.13.amd64 IIRC. could pretty easily separate that from whatever it's currently mixed with

**Comment by dougbu** [comment]
A complete solution here is likely either
1. #768 i.e., avoid unknown artefact versions on on-prem machines
2. for Python, validate new helix-scripts/ bundles on machines with current `python` and `pip` versions installed
  - unfortunately, when this fails, need (1) to move forward w/ new versions. therefore likely not worth it

I prefer to do (1) alone and to validate OSX using a fake osx.13.arm64 queue instead of the current osx.1100.amd64. Suggest we focus this issue on the second part of that.

**Comment by dougbu** [comment]
I think the high order bit here would be funding #768. I'm not sure how much work that would be b/c I haven't seen what @garath did for his `pip` update scripting. cleaning machines and redoing their artefacts is certainly achievable.

in particular, [!34916](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34916) helps but is incomplete. the root cause of our OSX and other on-prem gremlins is the fact mac.yaml and some of linux.yaml are just lies about some point in the past. we need to roll out to these machines on a regular basis &mdash; ideally more often then when we change artefacts (b/c vendor artifacts update frequently).

once we have that PR and #768 done, the remaining work would be to automate testing w/ a handful of staging on-prem machines. testing should focus on confirming the next rollout to the rest of the machines in our labs will succeed. not sure we have the budget or even the issue for that (yet).

/fyi @garath and @ilyas1974, I updated the issue description to cover the interim work from [!34916](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34916) only. you'll likely need follow-on issues, sorry.

**Comment by dougbu** [comment]
[!34916](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34916) fix rolled out 16 November '23
