### ISSUE TITLE
The build analysis tab is not showing good results for some SDK failures

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/dnceng#1803]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

This doesn't happen every time but here's an example where someone from another team was struggling to track down the test results failure for an SDK PR:
https://github.com/dotnet/sdk/runs/19545260835

You'lll see on the page that it lists the specific test that failed but didn't include the stack trace from the failure. BTW, it should really not show the helix work item failure as that's not generally useful data. Is there a way to remove that from the results (either something the SDK can do in how we publish test results or how build analysis analyzes the results).

Also, the [details links](https://dev.azure.com/dnceng-public/public/_build/results?buildId=496352&view=ms.vss-test-web.build-test-results-tab&runId=11535118&resultId=103460&paneView=debug) into AzDO do not show the test results (the error message and stack trace sections are blank). This has been a bug in AzDO for months if not longer. Has it been reported to them and can we get them to take a look?

**Comment by AlitzelMendez** [comment]
Hi Marc, 

Build Analysis relies on the error message and stack trace from AzDO to show this information, if this information is not present on AzDO we are not gathering this information from any other place, so this is the reasons the information is not in there. 

We haven't reported this to AzDO as is not a widespread issue, could this be specific to some tests? I am mentioning this because I was looking at this build: [Pipelines - Run 20240118.65 (azure.com)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=532980&view=ms.vss-test-web.build-test-results-tab&runId=12577342&paneView=debug) and in different queues the test that were not reporting result any additional information were the same.

**Comment by AlitzelMendez** [comment]
I don't think there is any action that build analysis can take on this, there reason the information is not showed is because is because the data is not on AzDO. 

The question is because why the information is not reported to AzDO, is an AzDO situation or something happening with the test, I will remove this issue from build analysis epic

**Comment by AlitzelMendez** [comment]
this doesn't seem to be a problem in our side, closing, please feel to reopen
