### ISSUE TITLE
Migrate dotnet-helix-machines-ci to use new 1ES Pipeline Templates

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1953]
Per direction from SLT, our AzDO pipelines should be making use of the 1ES Pipeline Templates. The `dotnet-helix-machines-ci` pipeline does not appear to be "Arcadified", so it should be more straight-forward to do the migration for this repo. 

Guidance in wiki: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1196/1ES-Pipeline-Template-Migration-Guidance

#### Steps

- [x] copy azure-pipeline.yml to create azure-pipeline-pr.yaml &mdash; [!37752](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37752)
- [x] create a new `dotnet-helix-machines-pr` pipeline referencing azure-pipeline-pr.yaml but otherwise looking very similar to [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596)
- [x] set policies to _not_ validate PRs in `dotnet-helix-machines-pr` if only azure-pipeline.yaml, azure-pipeline-image-generation.yaml, or templates only they use change &mdash; [!38158](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38158) and in AzDO policies
- [x] bump Arcade dependencies &mdash; [!38159](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38159)
- [x] modify azure-pipeline-image-generation.yaml and the templates it uses to extend the 1ES pipeline templates &mdash; [!38190](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38190)
- [x] modify azure-pipelines.yml and the templates it uses to extend the 1ES pipeline templates &mdash; [!38585](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38585)
- [x] remove the [dotnet-helix-machines-codeql](https://dev.azure.com/dnceng/internal/_build?definitionId=1089) pipeline

### Release Note Category

- [ ] Feature changes/additions
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Updated our official image generation pipelines ([dotnet-helix-machines-image-generation](https://dev.azure.com/dnceng/internal/_build?definitionId=1037) and [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596) to use 1ES pipeline templates. Also created a new [dotnet-helix-machines-pr](https://link.remains.tbd) pipeline specifically for pull requests.

**Comment by dougbu** [comment]
Steps:
- [x] copy azure-pipeline.yml to create azure-pipeline-pr.yaml &mdash; [!37752](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/37752)
- [ ] create a new `dotnet-helix-machines-pr` pipeline referencing azure-pipeline-pr.yaml but otherwise looking very similar to [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596)
- [ ] set policies to validate PRs in [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596) if only azure-pipeline.yaml or the (few) local templates it uses change
- [ ] optionally, set policies to validate PRs in [dotnet-helix-machines-image-generation](https://dev.azure.com/dnceng/internal/_build?definitionId=1037) if only azure-pipeline-image-generation.yaml or the templates it uses change
   - may not need this because manual builds have seemed sufficient so far
- [ ] set policies to _not_ validate PRs in `dotnet-helix-machines-pr` if only azure-pipeline.yaml, azure-pipeline-image-generation.yaml, or templates only they use change
- [ ] modify azure-pipelines.yml and the templates it uses to extend the 1ES pipeline templates
- [ ] modify azure-pipeline-image-generation.yaml and the templates it uses to extend the 1ES pipeline templates
- [ ] remove the [dotnet-helix-machines-codeql](https://dev.azure.com/dnceng/internal/_build?definitionId=1089) pipeline

**Comment by missymessa** [comment]
@garath do you want to move this issue to your epic?

**Comment by dougbu** [comment]
either way, I probably shouldn't be working on this this week (while I'm on Ops). that is, I'm now disagreeing w/ the `Ops - Compliance` label. agreed❔

**Comment by dougbu** [comment]
/fyi this pipeline isn't straightforward due to some unique things it does e.g., publishing in PRs

**Comment by garath** [comment]
> either way, I probably shouldn't be working on this this week (while I'm on Ops). that is, I'm now disagreeing w/ the Ops - Compliance label. agreed❔

Yep, this is now out of Ops and part of the spike dotnet/dnceng#2118.

**Comment by dougbu** [comment]
Coming back to this after time on FR and Ops, I realize worrying about PRs in the `-ci` pipeline to validate azure-pipelines.yml changes are not worthwhile. Manual builds should do the trick and the additional complications in the YAML are wasted. Further, PRs in this repo deploy assets into shared containers such as https://pkgs.dev.azure.com/dnceng/public/_packaging/helix-client-pr/pypi and the HelixStaging subscription. We'd need either new containers or new naming conventions to avoid conflicts due to branch name and build number overlaps between the `-ci` and `-pr` pipelines. I'm going to throw what I've done in that area away.

/fyi the naming convention I'd chosen for queues built in `-ci` PRs (a new `"ci-"` prefix) would even have required changes in the Helix SDK (`JobDefinition` special cases `"pr-"` at the moment)😦

**Comment by garath** [comment]
@dougbu I see the pipeline updates were merged. Yay! Good to close this issue?

**Comment by dougbu** [comment]
> @dougbu I see the pipeline updates were merged. Yay! Good to close this issue?

I don't think so. Let's wait until this merges into 'production'.

**Comment by dougbu** [comment]
Build of 'production' branch required a hotfix due to a missing artefact: [!38711](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38711)

**Comment by dougbu** [comment]
done
