### ISSUE TITLE
Known issue does not have regular updates

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/dnceng#2049]
The following known issue is not receiving regular updates to hits.  The summary and table to latest occurrences is missing.

https://github.com/dotnet/runtime/issues/95943

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by AlitzelMendez** [comment]
The reason for this is because this issue was removed from Known Build Errors project
<img width="640" alt="image" src="https://github.com/dotnet/dnceng/assets/6895254/83a90afa-e7bb-43da-b01c-6d72cd1bc2b1">

I added it back and the summary table is now getting posted and updated. 

Please feel free to reopen the issue if you observe other problem
