### ISSUE TITLE
Systems running in Staging (update documentation)

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2083]
I noticed recently that we are running a machine in each of our pools within the staging environment - regardless of usage. I think this is in error. 

Can you please investigate?

**Comment by AlitzelMendez** [comment]
This was a secret problem.

Autoscaler was unable to put the machines offline (the first step to get them deleted) because the Helix api token was not the correct one. It seemed that the secret was granting access to production instead of staging. I fixed the secret, but on top of that, I had to restart the VMs where the autoscaler is hosted to get this fixed.

So this is now working, and this issue is resolved, but we should probably follow up on this:
- We did not realize that this happened for a very long time. Do we need more tests or more alerts for this? In prod, it is easy to find out because this escalates quickly, but staging is not that easy, and it is expensive to be in this state.
- Is there a way to make this secret rotation easier? The secret was pointing to prod instead of staging. When you rotate the secret, it provides you the link that you need to use ` https://helix.int-dot.net/Account/Tokens`, but I do not know if we can do more.
- This secret did not get auto-updated. We need to fix this as part of passing the secret in a different way.

**Comment by AlitzelMendez** [comment]
Details for future investigation

Problem:
- Autoscaler is unable to delete machines because it is unable to put the machine "Offline"

Symptoms:
- VMs machines are not getting deleted
  - For staging this will translate in one machine always been alive, this can be observed in Grafana: [Queue Monitor - Grafana (azure.com)](https://dotnet-eng-grafana-staging.westus2.cloudapp.azure.com/d/queues/queue-monitor?orgId=1&refresh=30s)  you can filter some queues such as "windows.10.amd64"
  - For production this will be more obvious, with queue with a lot of machines, and most likely running out of quota

Verify it his is happening:
- Run the following query, if the count is bigger than 0, it means autoscaler is unable to delete the machines for HelixApiToken. For staging: [Go to Log Analytics and run query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fdotnet-eng-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22QQWtCMRCE7%252F0Viyel8KzgqVRBaqE9PA9qz7Imoy%252BQZB%252FJxkrpj2%252BU1l56nJ39hmFwNujVScx3X%252FTRIYHUBWTl0NOc%252BCjDSTe6ecZLsbu1eKw4gGYzGhx4n5x5HL%252FCu%252FN4UVQ2hj0WRiVtkE7OYHDj%252ByR7j%252FBmr2jrTJIsB22Woitoc81onr1D1GZdWyx69%252FLbkFjp3%252FimZdO5iJYjHxEqe%252F%252B0gYfRHyNvZVm1Ym53u2nTygkrnPWvlhRFapFz5clIVHYx02DbgRJyX9e5nWGJI7l4Yu8s1Z205OpZ0PRhQu%252BRi3aS3CfsJT6XEPii6kuJOhx9A8UBY5JwAQAA)  / For prod: [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22QQWtCMRCE7%252F0Viyel8KzgqVRBaqE9PA9qz7Imoy%252BQZB%252FJxkrpj2%252BU1l56nJ39hmFwNujVScx3X%252FTRIYHUBWTl0NOc%252BCjDSTe6ecZLsbu1eKw4gGYzGhx4n5x5HL%252FCu%252FN4UVQ2hj0WRiVtkE7OYHDj%252ByR7j%252FBmr2jrTJIsB22Woitoc81onr1D1GZdWyx69%252FLbkFjp3%252FimZdO5iJYjHxEqe%252F%252B0gYfRHyNvZVm1Ym53u2nTygkrnPWvlhRFapFz5clIVHYx02DbgRJyX9e5nWGJI7l4Yu8s1Z205OpZ0PRhQu%252BRi3aS3CfsJT6XEPii6kuJOhx9A8UBY5JwAQAA)


How to fix it:
1. Verify if the secret was recently rotated, depending in which instance this is happening
    - If the secret has been rotated recently follow to step 2
    - If the secret hasn't been rotated, rotate the secret with secret manager and the continue to step 2. Please make sure to rotate the secret for the right instance
2. Once the secret has been rotated, restart the autoscaler vm instances 
   - For production:  [dotnet-eng-helix-c1-Primary - Microsoft Azure](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourceGroups/dotnet-eng-helix-cluster-1/providers/Microsoft.Compute/virtualMachineScaleSets/dotnet-eng-helix-c1-Primary/overview)
   - For staging: [dotnet-eng-helix-int-c1-Primary - Microsoft Azure](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cab65fc3-d077-467d-931f-3932eabf36d3/resourceGroups/dotnet-eng-helix-int-cluster-1/providers/Microsoft.Compute/virtualMachineScaleSets/dotnet-eng-helix-int-c1-Primary/overview)
   - After the restart finished, wait 30 minutes and run the query to verify there are not more failures happening in the last 15 minutes 

If this continue failing, for the secret rotation again, in case this was rotated incorrectly the first time, make sure to rotate for the right instance (production or staging), secret manager should be provide clear steps on how to rotate depending on the instance, after this has been rotated follow the steps described above.

**Comment by ilyas1974** [comment]
adding this information to https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1053/Helix-Machines-(Notes-from-the-Field) for future reference. Closing issue.
