### ISSUE TITLE
Replace SetupNuGetSources.ps1

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#2127]
SetupNuGetSources.ps1 is a legacy tool that was designed to workaround NuGet issues in the .NET 3.1 timeframe. it's time to switch to using `NuGetAuthenticate@1`, avoiding username / password credentials completely.

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Updated Arcade's pipeline templates to avoid SetupNuGetSources.ps1 use and removed that script. This is been done in the following Arcade branches:
- [x] release/6.0
- [x] release/7.0
- [x] release/8.0
- [x] main

**Comment by rmarinho** [comment]
Just adding a comment because I want to track this work , we have a copy of this script , and use it on DevDiv. In future versions if we can make it a way it also still usable by people outside "arcade ecosystem" .

We just patched the script for get compliant for now. https://github.com/dotnet/maui/pull/20728/files#diff-791ba8fa491ce194de178cbb5c5d25ea680cc895a75072cde407589d47780768L28-R28

**Comment by dougbu** [comment]
related to #2135 as well. or, perhaps, that issue is another way to achieve the same ends

**Comment by missymessa** [comment]
PR: https://github.com/dotnet/arcade/pull/14553

**Comment by missymessa** [comment]
Backported to all servicing branches. Closing this issue!
