### ISSUE TITLE
Build analysis is not blocking pull request when the analysis hasn't finish as it is returning neutral instead of in_progress

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#2388]
Runtime is using build analysis as a required check to merge their pull request, but build analysis doesn't block a pull request when is expecting for results as it is returning the status of "Neutral"

There were a couple of conversation in which this was decided (The neutral status) when this work started, one of this comments: https://github.com/dotnet/arcade/issues/7466#issuecomment-854126409

We need to digger explore if there were more reasons behind this decision, some of my guesses are that build analysis wasn't reliable when this project started, at this point it is a lot more reliable, so probable we can try this out now.

but also, there could be other reasons, I need to make an investigation to be sure that this is not going to impact negatively any repository, if it does, we can discuss other options. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Build analysis can return an `in_progress` status while waiting for builds to finish, instead of `neutral`, for onboarded repositories.

**Comment by riarenas** [comment]
Capturing feedback from @missymessa here:

Currently, because of the neutral status of the check, repositories that don't have complicated check requirements currently just need to wait for the Azure devops build to finish. 

If we change the status, now repositories need to wait for both azure devops, and build analysis, so repositories might have to change the way their required checks are configured if they want to keep the existing behavior.

The antipattern here is to introduce a behavior change that will need any changes in all repositories that don't need this feature, so ideally we isolate any changes to repos that use this feature.

**Comment by AlitzelMendez** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/38609

**Comment by AlitzelMendez** [comment]
this was rolled out and validated, closing
