### ISSUE TITLE
Remove CentOS and RedHat from the Helix environment

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/dnceng#3189]
CentOS and RedHat meet the EOL date on 2024-06-30, once the customers stop using them, they should be removed.

### Release Note Category

- [x] Feature changes/additions
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

Removed the queues for CentOS and RedHat i.e., all `centos.7.amd64*` and `redhat.7.amd64*` queues.

**Comment by ilyas1974** [comment]
We need to work with the product teams to make sure workloads are moved to other queues before these are removed.

**Comment by dougbu** [comment]
CentOS 7 is in a worse state than RedHat 7 b/c RedHat at least has an extended support option for RedHat 7. CentOS 7 is completely EOL as of 30 June '24. I'm pretty sure we can't create CentOS 7 images anymore. Will test&hellip;

### A few details

Performance, runtime, and wcf runtimes still use the `centos7.amd64[.open]`, even over the past week. 

See [Teams conversation](https://teams.microsoft.com/l/message/19:1dad2081c8634f34915d88dce6220265@thread.skype/1719951350373?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1719951350373&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=Arcade&createdTime=1719951350373) and [Delete CentOS 7 Dockerfiles PR](dotnet/dotnet-buildtools-prereqs-docker#1123) reasoning. Note workarounds for missing package repo mirror choice site don't make new package updates available for the OS.

**Comment by dougbu** [comment]
>  I'm pretty sure we can't create CentOS 7 images anymore. Will test&hellip;

Turns out image generation has no problems installing CentOS 7 packages though one of the RedHat changes to "incentivize" moving off that OS was to disable the service used to choose between package repository mirrors. See [!40896](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/40896), success of `MakeImage` operations in [#20240706.01](https://dev.azure.com/dnceng/internal/_build/results?buildId=2489641&view=results), and agent logs in [Image Factory run 9b16eda7-4b1b-5f13-94c9-0592dab9de75](https://imagefactoryv3-webapi-ase-pme.azurewebsites.net/logs?TrackingId=9b16eda7-4b1b-5f13-94c9-0592dab9de75).

In addition, execute in [[Web](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAAzVMuwoCMRDs%2FYrhKoW0toIWglcI6v3AXrKYiGbDJkEO7uPNiRYzDPPqZcyrGW%2FPyrhUrrx%2FBsrwDZ3lWCR3oOhwDDFkzw470F3WW7dps6TyYFvQy3hyBjepatlgmFLj79viFtKyiP%2FFLzrTq7WunCSHIjoZHJSi9R8IdnMikwAAAA%3D%3D)] [[Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAAAzVMuwoCMRDs%2FYrhKoW0toIWglcI6v3AXrKYiGbDJkEO7uPNiRYzDPPqZcyrGW%2FPyrhUrrx%2FBsrwDZ3lWCR3oOhwDDFkzw470F3WW7dps6TyYFvQy3hyBjepatlgmFLj79viFtKyiP%2FFLzrTq7WunCSHIjoZHJSi9R8IdnMikwAAAA%3D%3D&web=0)] [[cluster('engsrvprod.kusto.windows.net').database('engineeringdata')](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata)]
``` kusto
Jobs
| where QueueAlias has "centos" and Finished > ago(5d)
| project JobId, Source, Type, Queued, Started, Finished, QueueName, Repository, Branch
```
shows numerous repositories and their pipelines continue to test on CentOS queues.

**Comment by dougbu** [comment]
Above Kusto query mixed up `QueueAlias` and `QueueName`. Correct version is
Execute in [[Web](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAAz2NsQoCMRBEe79iuEohhWBvYSF4heDpD%2Bwli4lgNuwmyIEf7x2ozfBgeDO9jLZ64xVZGZfGjc%2F0ZEQydJ5zFetAOeCYcrLIAXvQXda7bdjMWlF5sK%2FoZTwFh6s09exwm8qc%2FzWHgYtYqqKTw0Ep%2B%2FitF6mS1gV%2BFx%2FbEdV4kwAAAA%3D%3D)] [[Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAAAz2NsQoCMRBEe79iuEohhWBvYSF4heDpD%2Bwli4lgNuwmyIEf7x2ozfBgeDO9jLZ64xVZGZfGjc%2F0ZEQydJ5zFetAOeCYcrLIAXvQXda7bdjMWlF5sK%2FoZTwFh6s09exwm8qc%2FzWHgYtYqqKTw0Ep%2B%2FitF6mS1gV%2BFx%2FbEdV4kwAAAA%3D%3D&web=0)] [[cluster('engsrvprod.kusto.windows.net').database('engineeringdata')](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata)]

Jobs
| where QueueName has "centos" and Finished > ago(30d)
| project JobId, Source, Type, QueueName, Repository, Branch, Queued, Started, Finished

or, for redhat:
Execute in [[Web](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAAz2NsQoCMRBEe79iuEohhWBvYSF4heDpD%2BwlixvBbNgkyIEf7x2ozfBgeDO9jmX1xkvYGJfGjc%2F0ZAgVdMZBqHagFHCMKRbhgD3oruvdNmxmLZs%2B2Ff0Op6Cw1WbeXa4TXnO%2F5rDwFlLrGqTw8EoefnWi1TJ6gK%2Fiw%2B7U6pqkwAAAA%3D%3D)] [[Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAAAz2NsQoCMRBEe79iuEohhWBvYSF4heDpD%2BwlixvBbNgkyIEf7x2ozfBgeDO9jmX1xkvYGJfGjc%2F0ZAgVdMZBqHagFHCMKRbhgD3oruvdNmxmLZs%2B2Ff0Op6Cw1WbeXa4TXnO%2F5rDwFlLrGqTw8EoefnWi1TJ6gK%2Fiw%2B7U6pqkwAAAA%3D%3D&web=0)] [[cluster('engsrvprod.kusto.windows.net').database('engineeringdata')](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata)]

Jobs
| where QueueName has "RedHat" and Finished > ago(30d)
| project JobId, Source, Type, QueueName, Repository, Branch, Queued, Started, Finished

----

Current data shows performance team has cleaned up their remaining use of the CentOS queue but RedHat use continues in at least aspnetcore (for release/6.0), arcade, and runtime pipelines.

Not sure how to resolve this w/o another discussion w/ .NET PMs or waiting for @ilyas1974 to return. One idea might be to remove the CentOS queue and start a conversation about RedHat. @garath and @markwilkie what are your thoughts❓

**Comment by dougbu** [comment]
all resolved. just waiting for #4334 fix to roll out

**Comment by dougbu** [comment]
all done
