### ISSUE TITLE
Cryptography version not working in some queues 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/dnceng#368]
After the rollout of 07/12 machines in the following queues stopped heart beating:
- ubuntu.1804.amd64.tiger.perf
- ubuntu.1804.amd64.tiger.perf.open
- osx.13.arm64
- osx.13.arm64.open

After some investigation it turns out that the problem is related with an update of the cryptography version, which is unable to build in those queues.

As a hotfix we are manually pointing to an old wheel with a version that was properly working on these queues, but an actual fix next to get in before we rollout again because if not we will break these queues again. 

### Release Note Category

- [ ] Feature changes/additions 
- [x] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Updated the version of `pip` used on OSX machines to one new enough to correctly install `universal2` packages. This installation requirement comes from many Python packages now using `universal2` tags (and contained assemblies) for M2 hardware.

**Comment by AlitzelMendez** [comment]
I did the helix scripts version update for osx.13.arm64 and osx.13.arm64.open and the machines are now heart beating 🥳 

but I don't see the same response on ubuntu.1804.amd64.tiger.perf.open even after the update the machines are not working, I will reboot them and investigate what could be happening

**Comment by dougbu** [comment]
> I will reboot them and investigate what could be happening

to confirm: that got things working @AlitzelMendez❔

**Comment by dougbu** [comment]
were the following queues also impacted after the rollout❔

- osx.13.arm64.appletv.open
- osx.13.arm64.m1.perf
- osx.13.arm64.m2.perf
- osx.13.arm64.iphone.open
- ubuntu.1804.amd64.owl.perf
- ubuntu.1804.amd64.snake.perf.open

**Comment by AlitzelMendez** [comment]
**osx.13.arm64.***
  The rest of the queues were not impacted although I think only osx.13.arm64.m2.perf has machines 
  
  ```
  HeartbeatExport
  | where ingestion_time() > ago(10d)  
  | where Queue contains "osx.13.arm64"
  | summarize max(LastHeartbeat) by Queue
```

**ubuntu.1804.amd64.owl.perf**: it wasn't impacted 
**ubuntu.1804.amd64.snake.perf.open** : there are no machines in this queue

**Comment by dougbu** [comment]
thanks @AlitzelMendez.

the Matrix of Truth says osx.13.arm64.iphone.open has one machine; it doesn't mention osx.13.arm64.m2.perf. of course, that report may be out of date.

**Comment by dougbu** [comment]
note the three osx.13.arm64.m2.perf machines haven't rebooted since 1 June and are still using the 20230531.2 script version.

Log at <https://helixagentlogs.blob.core.windows.net/agent-logs/osx.13.arm64.m2.perf/dci-macm2-build-048/2023-07-14T18.19.29Z.log> shows

``` text
2023-07-14T19:05:13.415Z	ERROR  	run_client.py	scriptutil(88)	check_for_updates	Error trying to update scripts / config : Traceback (most recent call last):
  File "/private/etc/helix/scripts/helix/scriptutil.py", line 61, in check_for_updates
    self._replace_helix_settings()
  File "/private/etc/helix/scripts/helix/scriptutil.py", line 125, in _replace_helix_settings
    self._download_to(self.settings_uri, settings_path)
  File "/private/etc/helix/scripts/helix/scriptutil.py", line 148, in _download_to
    raise Exception("Failed to download '{}', the status code was {}.".format(str(uri).split("?")[0], response.status_code))
Exception: Failed to download 'https://helixosconfig.blob.core.windows.net/configuration/osx.13.arm64.m2.perf.zip', the status code was 403.
```

@ilyas1974 is this a known (separate of course) issue❔

**Comment by dougbu** [comment]
Ugh, many `ubuntu.1804.amd64.tiger.perf[.open]` machines are happily heart-beating while still running the supposedly-bad 20230711.2 script. On the other hand, PERFTIGER185 has the older "better" script version but hasn't been heard from since the 12th and last rebooted on the 1st.

Unless I hear different, I'll look at PERFTIGER185 and one or two of the giddy-with-20230711.2 machines after lunch.

**Comment by dougbu** [comment]
partial information:
- the old script (aka old `cryptography` version range) used cryptography-3.4.6-cp36-abi3-macosx_11_0_arm64.whl on the OSX 13 ARM64 machines. 
- since `cryptography` v37.0.0, the package has only shipped `universal2` packages for macOS on ARM64 hardware
- we're using Python 3.9.13 on all macOS machines and that should support `universal2` packages
- however, the OSX 13 machines may lack Rosetta 2 (earlier macOS machines may have run Intel s/w at some point, picking up Rosetta 2)
- command to install and check installation of Rosetta 2 is `softwareupdate --install-rosetta --agree-to-license`

I have not yet checked the "may lack Rosetta 2" hypothesis.

**Comment by dougbu** [comment]
I wasn't correct to suspect earlier macOS machines had run Intel s/w at some point. the difference appears to be that cryptography-41.0.2-cp37-abi3-macosx_10_12_x86_64.whl is compatible w/ M1 hardware. Wild

**Comment by dougbu** [comment]
&hellip; and our OSX 11 and 12 machines all seem to be on M1 hardware. we don't have any OSX 14 (scouting) machines and OSX 13 machines are all on M2. That's likely where the problem lies.

I took osx.13.arm64.open / dci-macm2-build-006 offline to see if I can get things working.

**Comment by dougbu** [comment]
I take that back about having no OSX 13 machines on M1 hardware: Three osx.13.arm64.m1.perf machines exist; they just aren't running Helix software at all and don't even have a /tmp/helix folder. (@ilyas1974 @LoopedBard3❔)

**Comment by dougbu** [comment]
Rosetta 2 installation wasn't the OSX 13  / M2 issue. Instead, the version of `pip` we're using doesn't support `universal2` tags correctly on macOS. Need at least `packaging` v20.9, which is included in `pip` v21.0.1 and newer. I successfully installed `cryptography` v41.0.2 after updating `pip` to v22.0.4. That's a bigger jump than we need but the first version after v21.0.1 currently available in netcorenativeassets.

**Comment by dougbu** [comment]
Checking other tiger.perf machines:

- `alpine.amd64.tiger.perf` machines look good w/ latest (20230711.2) script version, except
  - `PERFTIGER158` last reported itself as offline (perhaps because I temporarily took it offline a few hours ago)
- `ubuntu.2204.amd64.tiger.perf` look good w/ latest script version except:
  - `PERFTIGER168` and `PERFTIGER169` last reported themselves as offline
  - `PERFTIGER179` exists in @ilyas1974's list of machines but has not had a heartbeat in the last 10 days
- `windows.10.amd64.19h1.tiger.perf[.open]` machines are heart-beating but remain at script version 20230531.2
  - a sample agent log shows they're in the same `403` state as the osx.13.arm64.m2.perf machines

**Comment by dougbu** [comment]
All `ubuntu.1804.amd64.tiger.perf` are currently busy but the `ubuntu.1804.amd64.tiger.perf.open` machines are not. Took `PERFTIGER210` offline to investigate&hellip;

The problem appears to be use of Python 3.6 and `pip` 19.0 when both are rather old. 3.7 is available on the Ubuntu 18.04 machines. I was able to successfully install `cryptography` v41.0.2 when using Python 3.7 and latest `pip` (v23.2). Will continue testing to see if using `pip` v20.3.1 is sufficient to install the newest `cryptography`. It's also unclear why the `pip` version isn't up to date on `PERFTIGER210`.

**Comment by dougbu** [comment]
Using `pip` v20.3.1 is sufficient. Main questions are:
- how to rerun `linux-pip` across all of the `ubuntu.1804.amd64.tiger.perf[.open]` machines
- why the artefacts aren't automatically kept up to date on these machines

It may also be useful to change the `linux-pip` scripts to always use the latest `python3.X` found on the machine. Perhaps even useful to do that across the places we currently check for `python3.6` and use that if it's newer than `python3`.

**Comment by dougbu** [comment]
To find newest Python (given Python 3.13 and 3.12 are in development), the following should work though it won't necessarily find the newest patch if (say) `python3.7` exists in multiple elements of the `$PATH`.

``` bash
python_path=$(for m in {14..6}; do
  if command -v python3.$m; then break; fi
done)
[ -z "$python_path" ] && python_path=$(command -v python3)
```

**Comment by dougbu** [comment]
Note the fix for both of these issues requires re-synchronizing artefacts across all affected machines. Changing helix-scripts can't happen on these machines before that is done. Due to the discrepancies observed, especially on `ubuntu.1804.amd64.tiger.perf[.open]` boxes, probably much better to update **all** on premise machines.

Going that broad probably can't happen until the `403` issues are resolved.

**Comment by dougbu** [comment]
@garath thoughts on putting this into the `Helix Machines improvements` milestone❔

**Comment by LoopedBard3** [comment]
> I take that back about having no OSX 13 machines on M1 hardware: Three osx.13.arm64.m1.perf machines exist; they just aren't running Helix software at all and don't even have a /tmp/helix folder. (@ ilyas1974 @ LoopedBard3❔)

@DrewScoggins Are you aware of anything with the osx.13.arm64.m1.perf machine queue? I am not aware of anything having to do with that queue.

**Comment by garath** [comment]
> thoughts on putting this into the Helix Machines improvements milestone

Hmmmm, I'm not sure yet. What would you propose the change be?

**Comment by dougbu** [comment]
> > thoughts on putting this into the Helix Machines improvements milestone
> 
> Hmmmm, I'm not sure yet. What would you propose the change be? It seems to me like no solid solution for the "cryptography package on old OSes" yet, or am I missing something?

We'll do three things to fix this issue:
- merge [!32698](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32698)
- update the artefacts deployed on on-premise machines
- resolve the `403` issue impacting `osx.13.arm64.m2.perf` and `windows.10.amd64.19h1.tiger.perf[.open]` boxen

**Comment by dougbu** [comment]
#377 covers what I called the "`403` issue" above. #379 is tactical work we must complete before we an do #377 (because some artefacts on the machines are too old to use the current helix client wheels).

**Comment by dougbu** [comment]
work here is complete. related work will continue in issues such as #768 and #769

**Comment by dougbu** [comment]
manual work reflected in production now. see also #418
