### ISSUE TITLE
Known issues are not matching against test results

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#3992]
Build analysis is not matching against errors found in test results, only in console logs. Is this expected or a bug?

FYI @missymessa 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
I dug through the Known Issues code (and I'll document this in the documentation), and here's where matches happen: 
  - Helix Work Item Console Log
  - Build logs
  - Error messages in steps of the build pipeline
  - Test Case Result Error Message
  - Test Case Result Stack Trace
 
Additionally, I was looking at the Known Issue that was created and noticed that the error message was applied to the "Error Pattern" field, rather than the "Error Message" field. "Error Pattern" is used for Regex matching, so that could also be a reason why the error wasn't being matched if the error showed up in any of the above locations. 

As the build this occurred on is now gone, I can't say for certain if this was a bug or not, but we have more information next time this occurs.

**Comment by missymessa** [comment]
Related documentation:
- ⁠https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-the-matching-process-works-between-a-known-issue-and-a-buildtest-error
- ⁠https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#fill-out-known-issues-with-a-list-of-errors
